name: Build Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21 (For Gradle Engine)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up JDK 25 (For Minecraft Toolchain)
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'

      - name: Setup Gradle 8.10
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.10'

      - name: Build with Gradle
        run: gradle build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
          ORG_GRADLE_PROJECT_jdk25Home: ${{ env.JAVA_HOME_25_X64 }}
